name: Change API key on dev during push

on:
  push:
    branches:
      - main

jobs:
  generate-apikey:
    runs-on: ubuntu-latest

    outputs:
      random_string: ${{ steps.generate.outputs.random_string }}

    steps:
      - name: Generate random string
        id: generate
        run: |
          RANDOM_STRING=$(openssl rand -hex 8) # 16 hex characters
          echo "Random string: $RANDOM_STRING"
          echo "random_string=$RANDOM_STRING" >> "$GITHUB_OUTPUT"
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
      - name: Change API_KEY Secret 
        run:  doppler secrets set API_KEY --project "$DOPPLER_TARGET_PROJECT" --config "$DOPPLER_TARGET_CONFIG" --silent  --no-interactive --raw "$RANDOM_STRING"
        shell: bash
      - name: Do CI CD things
        run: echo "Secret created at Doppler and added to GitHub. Now we can deploy stuff."
      - name: Delete API_KEY Secret 
        run: doppler secrets delete API_KEY --project "$DOPPLER_TARGET_PROJECT" --config "$DOPPLER_TARGET_CONFIG" --silent  --no-interactive 
        shell: bash
      - name: secret deleted
        run: echo "new secret deletedfrom Doppler & GitHub"  
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEV }}
          DOPPLER_TARGET_PROJECT: ${{ secrets.DOPPLER_TARGET_PROJECT }}
          DOPPLER_TARGET_CONFIG: ${{ secrets.DOPPLER_TARGET_CONFIG_DEV }}
          RANDOM_STRING: ${{ steps.generate.outputs.random_string }}


       